### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by bhansa** [ashwini0529/vit-faculty-database#1]
Hey bro, I just checked your repo and find out you are working on scraping, I need the data and for it I was gonna write the script for scraping.
Please continue what you are working on.

**Comment by ashwini0529** [comment]
I have made the script. I will push updates after a day or two. :)

**Comment by abhinav-adtechs** [comment]
Please _**continue**_ what you are working on. :)

**Comment by ashwini0529** [comment]
Sure :)
